Create 3-0-implementation-plan.md
avuim/publisher-curated-auctioning pull request #6
Opened 2022-09-16 09:53 UTC by avuim

Initial proposal of MVP backlog for implementation stages into committed  SSP/DSPs

2022-09-16 09:55 UTC, avuim commented
Protocol of our call from 12th Sep 2022

2022-09-16 12:39 UTC, asr-enid requested changes

2022-09-16 12:39 UTC, asr-enid commented on 3-0-implementation-plan.md
> +* Adherence of (SSP to DSP) "authorized connections" restriction configuration
For the sake of completeness 

"Adherence to (Publisher to SSP, SSP to DSP) "authorized connections" restriction configuration

2022-09-16 12:39 UTC, asr-enid commented on 3-0-implementation-plan.md
> +* Adherence of DSP "seat level" restriction configuration but without "authorized feature" binding
Need to cycle back on this not sure what we mean by this

2022-09-16 12:39 UTC, asr-enid commented on 3-0-implementation-plan.md
> +* No restriction of internal DSP graph usage (e.g. Adform Fusion ID, VirtualMinds Any ID)
My understanding was that Graph Usage (yes/no generally not seat specific) per ID is a must to be configurable (and is possible already)

2022-09-16 12:39 UTC, asr-enid commented on 3-0-implementation-plan.md
> +* but no ID exposure, since ID export per default deactivated
See above I think both is part of I and also possible

2022-09-16 12:39 UTC, asr-enid commented on 3-0-implementation-plan.md
> +* Partially adherence of "authorized feature" config especially in respect of IDs being used in DSP internal graphs or not
See above

2022-09-16 15:31 UTC, avuim commented on 3-0-implementation-plan.md
> +* No restriction of internal DSP graph usage (e.g. Adform Fusion ID, VirtualMinds Any ID)
@jsr-adf clearly statet, that the internal usage (e.g. Fusion ID Graph) cannot be restricted in the first step but not external exposure of ID takes place, therefore "could" be accepted in combination with contractual agreement. Jochen, maybe you comment on this.

2022-09-16 15:33 UTC, avuim commented on 3-0-implementation-plan.md
> +* Adherence of (SSP to DSP) "authorized connections" restriction configuration
yeah, dont't mind, but Pub to SSP/bidder ist anyway possible with prebid config by now, therefore no implementation requirement in my opinion.

2022-09-16 15:36 UTC, avuim commented on 3-0-implementation-plan.md
> +* Adherence of DSP "seat level" restriction configuration but without "authorized feature" binding
Complying with config for SSP to DSP signalling down to seat level but without the detail individual control of features on seat level, but rather globally per DSP (e.g. no raw ID export)

2022-09-16 15:37 UTC, avuim commented on 3-0-implementation-plan.md
> +* but no ID exposure, since ID export per default deactivated
Let's discuss in next call

2022-11-23 08:54 UTC, halthauser commented on 3-0-implementation-plan.md
> +* Adherence of (SSP to DSP) "authorized connections" restriction configuration
Ok with [avuim](https://github.com/avuim)

2022-11-23 08:56 UTC, halthauser commented on 3-0-implementation-plan.md
> +* Adherence of DSP "seat level" restriction configuration but without "authorized feature" binding
Ok with [avuim](https://github.com/avuim)

2022-11-23 08:57 UTC, halthauser commented on 3-0-implementation-plan.md
> +* No restriction of internal DSP graph usage (e.g. Adform Fusion ID, VirtualMinds Any ID)
Also on the same page w/ [avuim](https://github.com/avuim), can't be restricted in the first step

2022-11-23 08:57 UTC, halthauser commented on 3-0-implementation-plan.md
> +* but no ID exposure, since ID export per default deactivated
Like discussed okay for us.

2022-12-15 08:15 UTC, merged